import curatedDict from './curated.json'

/**
 * A bundled, offline canon of widely-famous songs, used as an objective
 * recognizability signal for the deck (independent of Deezer play counts).
 *
 * Provenance & legal hygiene: aggregated from public, factual chart/critic
 * data on Wikipedia and an aggregator — Billboard Year-End Hot 100 (1959–2024),
 * German/Austrian/Swiss #1 singles, and songs on ≥2 of ~20 "greatest songs"
 * lists. Song titles and chart positions are plain facts (not copyrightable),
 * and the combined set is nobody's single creative arrangement. Generated by an
 * out-of-repo script; only the data is committed.
 *
 * Stored grouped by region (`{ intl: {Artist:[Title,…]}, de:{…}, at:{…}, ch:{…} }`)
 * so the app can later localize (weight the player's country). `intl` is the
 * Billboard + greatest-songs canon; `de`/`at`/`ch` are per-country #1 singles.
 * Matching normalizes both sides identically (strip parentheticals, quotes,
 * "feat…", leading articles → alphanumeric tokens).
 */
function norm(s: string): string {
  return (s || '')
    .toLowerCase()
    .replace(/\([^)]*\)|\[[^\]]*\]/g, ' ') // "(Remastered)", "[Live]", "(1965)"
    .replace(/["'“”‘’]/g, '')
    .replace(/\bfeat(uring)?\.?\b.*$/, ' ') // "feat. X", "featuring X"
    .replace(/\b(the|a|an|die|der|das)\b/g, ' ')
    .replace(/[^a-z0-9]+/g, ' ')
    .trim()
}

/** The same normalization, for matching any name across servers (see exclusions). */
export { norm as normalizeName }

/** Normalized artist token — used to test whether a library artist is in the canon. */
export function artistKey(artist: string): string {
  return norm(artist)
}

export function curatedKey(artist: string, title: string): string {
  return `${norm(artist)}┃${norm(title)}`
}

export interface CuratedEntry {
  artist: string
  title: string
  /** The lists it is on (`intl`, `de`, …) — a song can top several. */
  lists: string[]
}

/** Region code → artist → titles. `intl` plus per-country #1s. */
type CuratedRegions = Record<string, Record<string, string[]>>
const curatedRegions = curatedDict as CuratedRegions

/** The bundled hit lists, in file order: `intl` first, then the countries. */
export const HIT_LISTS: string[] = Object.keys(curatedRegions)

export const curatedEntries: CuratedEntry[] = []
const CURATED = new Map<string, CuratedEntry>()
for (const [list, region] of Object.entries(curatedRegions)) {
  for (const [artist, titles] of Object.entries(region)) {
    for (const title of titles) {
      const k = curatedKey(artist, title)
      const known = CURATED.get(k)
      if (known) {
        if (!known.lists.includes(list)) known.lists.push(list)
      } else {
        const entry = { artist, title, lists: [list] }
        CURATED.set(k, entry)
        curatedEntries.push(entry) // deduped across lists
      }
    }
  }
}

/**
 * Is this entry on one of the chosen lists? None chosen (undefined or empty)
 * means every list.
 */
export function onHitLists(entry: CuratedEntry, lists?: string[]): boolean {
  return !lists?.length || entry.lists.some((l) => lists.includes(l))
}

/** Is this song part of the famous-songs canon (on the chosen lists, if any)? */
export function isCurated(artist: string, title: string, lists?: string[]): boolean {
  const entry = CURATED.get(curatedKey(artist, title))
  return !!entry && onHitLists(entry, lists)
}
