import curatedDict from './curated.json'

/**
 * A bundled, offline canon of widely-famous songs, used as an objective
 * recognizability signal for the deck (independent of Deezer play counts).
 *
 * Provenance & legal hygiene: aggregated from public, factual chart/critic
 * data on Wikipedia and an aggregator — Billboard Year-End Hot 100 (1959–2024),
 * German/Austrian/Swiss #1 singles, and songs on ≥2 of ~20 "greatest songs"
 * lists. Song titles and chart positions are plain facts (not copyrightable),
 * and the combined set is nobody's single creative arrangement. Generated by an
 * out-of-repo script; only the data is committed.
 *
 * Stored grouped by region (`{ intl: {Artist:[Title,…]}, de:{…}, at:{…}, ch:{…} }`)
 * so the app can later localize (weight the player's country). `intl` is the
 * Billboard + greatest-songs canon; `de`/`at`/`ch` are per-country #1 singles.
 * Matching normalizes both sides identically (strip parentheticals, quotes,
 * "feat…", leading articles → alphanumeric tokens).
 */
function norm(s: string): string {
  return (s || '')
    .toLowerCase()
    .replace(/\([^)]*\)|\[[^\]]*\]/g, ' ') // "(Remastered)", "[Live]", "(1965)"
    .replace(/["'“”‘’]/g, '')
    .replace(/\bfeat(uring)?\.?\b.*$/, ' ') // "feat. X", "featuring X"
    .replace(/\b(the|a|an|die|der|das)\b/g, ' ')
    .replace(/[^a-z0-9]+/g, ' ')
    .trim()
}

/** Normalized artist token — used to test whether a library artist is in the canon. */
export function artistKey(artist: string): string {
  return norm(artist)
}

export function curatedKey(artist: string, title: string): string {
  return `${norm(artist)}┃${norm(title)}`
}

export interface CuratedEntry {
  artist: string
  title: string
}

/** Region code → artist → titles. `intl` plus per-country #1s. */
type CuratedRegions = Record<string, Record<string, string[]>>
const curatedRegions = curatedDict as CuratedRegions

export const curatedEntries: CuratedEntry[] = []
const CURATED = new Set<string>()
const seenEntry = new Set<string>()
for (const region of Object.values(curatedRegions)) {
  for (const [artist, titles] of Object.entries(region)) {
    for (const title of titles) {
      const k = curatedKey(artist, title)
      CURATED.add(k)
      if (!seenEntry.has(k)) {
        seenEntry.add(k)
        curatedEntries.push({ artist, title }) // deduped across regions
      }
    }
  }
}

/** Is this song part of the famous-songs canon? */
export function isCurated(artist: string, title: string): boolean {
  return CURATED.has(curatedKey(artist, title))
}
